
name: "Main Pipeline"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-and-validate:
    name: "Build and Validate"
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
   